---

- name: Update apps
  become: true
  become_user: "{{ user }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
    version: "{{ item.version }}"
    force: "{{ item.force | default() | bool }}"
    accept_hostkey: True
  with_items: "{{ common_deployment_apps | default([]) }}"
  when:
    - common_deployment_apps is defined
  tags:
    - apps
    - deploy
    - update
