---

- name: Update apps
  become: true
  become_user: "{{ user }}"
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ item.value.location }}"
    version: "{{ item.value.version }}"
    accept_hostkey: True
  with_dict: "{{ common_deployment_apps | default({}) }}"
  when:
    - common_deployment_apps is defined
    - "user != 'vagrant'"
  tags:
    - apps
    - deploy
    - update
